version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myPassword
    ports:
      - 27017:27017
  poc:
    build: .
    ports:
      - 3000:3000
    links:
      - 'mongo:database'
